version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "jdbc:postgresql://db.aiiyrgotzcdwejgjlwvz.supabase.co:5432/postgres?sslmode=require"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "123Thineth//"
      CLERK_JWKS_URL: "https://faithful-halibut-62.clerk.accounts.dev/.well-known/jwks.json"