services:
  app:
    image: cic-asset-inventory:lts1
    container_name: skill-mentor-backend
    ports:
      - "8085:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
      - USERNAME=${DB_USERNAME:-postgres}
      - PASSWORD=${DB_PASSWORD:-123Thineth//}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

volumes:
  postgres_data: