spring.application.name=inventory
spring.profiles.active=prod

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://asset-postgres:5432/assetdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123Thineth//}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Colombo

# JWT
jwt.secret=${JWT_SECRET:asset2026@IntranetSecretKey#Thineth!XyZ789abcd}
jwt.access-token-expiration-minutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:60}
jwt.refresh-token-expiration-days=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:7}

# CORS
CORS_ALLOWED_ORIGINS=http://192.168.8.50:81,https://cicinventory.netlify.app
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3001}

server.port=${SERVER_PORT:8081}