spring.application.name=inventory

spring.profiles.active=prod

# Prod
# ---

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Colombo

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db.aiiyrgotzcdwejgjlwvz.supabase.co:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123Thineth//}

#jdbc:postgresql://db.aiiyrgotzcdwejgjlwvz.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5433/cic_inventory
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver