# Additional DB Configurations
# ===
spring.jpa.hibernate.ddl-auto=update
logging.level.root=ERROR

# Authentication Configuration (Clerk)
# ===
auth.validator.type=clerk

# Prod
clerk.jwks.url=${CLERK_JWKS_URL:https://faithful-halibut-62.clerk.accounts.dev/.well-known/jwks.json}

# CORS set to your Vercel frontend URL on Render once deployed
CORS_ALLOWED_ORIGINS=https://cicinventory.netlify.app/,http://localhost:3001
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3001}